sudo: true

language: python

python: 3.7

cache:
    - pip

before_install:
    - sudo apt update
    - sudo apt install -y quantum-espresso
    - wget http://folk.uio.no/anjohan/lmp
    - chmod u+x lmp

install:
    - pip install -r requirements.txt

script:
    - cd tests
    - PWSCF_COMMAND=pw.x lmp=../lmp pytest --cov=../
    - coverage xml

after_success:
    - codecov
