sudo: true

language: python

python: 3.7

cache:
    - pip

before_install:
    - sudo apt update
    - sudo apt install -y quantum-espresso 
    - pip install codecov pytest pytest-cov pytest_mock
    - git clone https://github.com/lammps/lammps.git lammps
    - pwd
    - ls
    - cp lammps_plugin/pair_mgp*.* lammps/src
    - cd lammps/src
    - make serial
    - cd ../..
    - "wget https://github.com/cp2k/cp2k/releases/download/\
      v7.1.0/cp2k-7.1-Linux-x86_64.sopt"
    - chmod u+x cp2k-7.1-Linux-x86_64.sopt
    - pip install -r requirements.txt

script:
    - pwd
    - cd tests
    - ls test_files
    - PWSCF_COMMAND=pw.x
      lmp=$(pwd)/../lammps/src/lmp
      CP2K_COMMAND=../cp2k-7.1-Linux-x86_64.sopt
      pytest -vv --durations=0 --cov=../flare/
    - coverage xml

after_success:
    - codecov
