sudo: false

language: python

python: 3.7

cache:
    - pip

install:
    - pip install codecov pytest pytest-cov numba memory_profiler numpy scipy

script:
    - cd tests && pytest --cov=../ && coverage xml && cp coverage.xml ..

after_success:
    - codecov
