sudo: true

language: python

python: 3.7

cache:
    - pip

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt update
    - sudo apt install -y quantum-espresso g++-9
    - pip install codecov pytest pytest-cov numba memory_profiler numpy scipy
    - wget http://folk.uio.no/anjohan/lmp
    - chmod u+x lmp

script:
    - cd tests
    - PWSCF_COMMAND=pw.x lmp=$HOME/lmp pytest --cov=../
    - coverage xml

after_success:
    - codecov
