ase_atoms: # Super cell
    file: POSCAR
    format: vasp
    replicate: [1, 1, 1]
    jitter: 0.1

ase_flare_calc: # FLARE calculator
    gp: GaussianProcess
    kernels:
        - twobody
        - threebody
    gp_parameters: 
        cutoff_twobody: 10.0
        cutoff_threebody: 6.0
    random_init_hyps: True
    opt_algorithm: L-BFGS-B
    n_cpus: 1
    use_mapping: False
    # (Optional)
    mgp: MappedGaussianProcess
    grid_params:
        twobody:
            grid_num: [64]
        threebody:
            grid_num: [16, 16, 16]
    var_map: pca

ase_dft_calc: # DFT calculaotr
    name: LennardJones
    kwargs: {}
    params:
        sigma: 3.0
        rc: 9.0

otf: # On-the-fly training and MD
    md_engine: VelocityVerlet
    md_kwargs: {}
    temperature: 1000
    dt: 0.001 # timestep is 1 fs
    number_of_steps: 5
    output_name: myotf
    init_atoms: [0, 1, 2, 3]
    std_tolerance_factor: 1.0
    max_atoms_added: -1
    freeze_hyps: 10
    write_model: 4
