# Adapted from: https://github.com/satu0king/Github-Documentation-With-Doxygen
# This is a basic workflow to help you get started with Actions

name: flare

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        pip install codecov pytest pytest-cov pytest_mock
        git clone --depth 1 -b stable_29Oct2020 https://github.com/lammps/lammps.git lammps
        cp lammps_plugins/pair_mgp.* lammps/src
        cd lammps/src
        make -j 2 serial CCFLAGS='-std=c++11'
        cd ../..
        pip install -r requirements.txt

    - name: Build
      run: |
        cd tests
        export lmp=$(pwd)/../lammps/src/lmp_serial
        pytest
